-- Auto-generated by sql/generate-migration-sql.js
-- Source: C:\Users\devinej\VisualStudioCodeProjects\Gantt.Planner\tasks-2026-04-23-10-19.json
-- Generated: 2026-04-23T09:20:43.228Z
-- Rows: 64

SET XACT_ABORT ON;
BEGIN TRAN;

-- Uncomment the next line to fully replace existing data:
-- TRUNCATE TABLE gantt.Tasks;

INSERT INTO gantt.Tasks (Person, TaskName, StartDate, EndDate, CapacityImpact, Complete, MilestonesJson)
VALUES
    (N'0.Unassigned', N'Kiosk off line clock in and use with security cards Q3', NULL, NULL, N'high', 0, N'{}'),
    (N'0.Unassigned', N'Review Scheduling Options', NULL, NULL, N'medium', 0, N'{}'),
    (N'0.Unassigned', N'B2C Replacement', NULL, NULL, N'low', 0, N'{}'),
    (N'0.Unassigned', N'Bulk uplift and increment processing - Ian Daykin Q4 -  see ASQ 10', NULL, NULL, N'low', 0, N'{}'),
    (N'0.Unassigned', N'Notification Catalogue', NULL, NULL, N'low', 0, N'{}'),
    (N'0.Unassigned', N'PAT Token Replacement', NULL, NULL, N'low', 0, N'{}'),
    (N'0.Unassigned', N'Profile Endpoint Review', NULL, NULL, N'low', 0, N'{}'),
    (N'0.Unassigned', N'Review Aggregate Data Coupling in Flyway', NULL, NULL, N'low', 0, N'{}'),
    (N'0.Unassigned', N'Absence Triggers Phase 2', NULL, '2026-12-31', N'low', 0, N'{}'),
    (N'Anthony', N'Skills', '2025-11-14', '2026-04-30', N'high', 0, N'{}'),
    (N'Anthony', N'Scheduling Improvements', '2026-03-26', '2026-04-03', N'medium', 0, N'{}'),
    (N'Anthony', N'Background Checks - Rightgen integration', '2025-11-14', '2026-05-29', N'medium', 0, N'{}'),
    (N'Anthony', N'WFM - Flexi Time', '2026-05-01', '2027-03-31', N'medium', 0, N'{"Team starts work (Q3)":"2026-07-01","Deliver (Q1)":"2027-01-01"}'),
    (N'Anthony', N'Absence Access Permissions', '2026-03-16', NULL, N'low', 0, N'{}'),
    (N'Anthony', N'SPIKE - Manager access to claims in payroll', '2026-02-18', '2026-02-27', N'low', 0, N'{}'),
    (N'Anthony', N'Document message flow for Payroll', '2025-11-14', '2026-03-31', N'low', 0, N'{}'),
    (N'Anthony', N'Tidy Up Documentation', '2026-01-26', '2026-04-28', N'low', 0, N'{}'),
    (N'Anthony', N'Documentation Site Support', '2025-11-14', '2026-04-30', N'low', 0, N'{}'),
    (N'JD', N'Payroll Architecture (Batch Messaging)', '2025-11-10', '2026-06-30', N'high', 0, N'{"GTN Report - Jacek":"2025-12-08"}'),
    (N'JD', N'Absence Triggers Phase 1', '2026-03-01', NULL, N'medium', 0, N'{}'),
    (N'JD', N'Container App Data - Cost, Size + Performance', '2026-03-04', NULL, N'medium', 0, N'{"Aspiration to start":"2026-03-18"}'),
    (N'JD', N'DLX/Attachments Support', '2025-11-01', NULL, N'medium', 0, N'{"First Release":"2026-03-05"}'),
    (N'JD', N'Expenses', '2026-04-06', NULL, N'medium', 0, N'{}'),
    (N'JD', N'Tilt  Integration (USA)', '2026-04-16', NULL, N'medium', 0, N'{}'),
    (N'JD', N'Contract Generation', '2026-02-10', '2026-03-13', N'medium', 1, N'{"Work Starts Q2":"2026-04-01","Contractual Commitment":"2026-06-01","4 weeks":"2026-03-10"}'),
    (N'JD', N'Finance - Multi Tenancy Info', '2026-03-10', '2026-03-31', N'medium', 1, N'{}'),
    (N'JD', N'Fleet Management', '2026-04-14', '2026-04-30', N'medium', 0, N'{"Review ASQ":"2026-04-14"}'),
    (N'JD', N'Policy Search HLD', '2026-02-27', '2026-04-30', N'medium', 0, N'{}'),
    (N'JD', N'Absence Access Permissions', '2026-03-05', '2026-05-31', N'medium', 0, N'{}'),
    (N'JD', N'Fitness Function Scoring Review', '2026-04-01', '2026-06-30', N'medium', 0, N'{}'),
    (N'JD', N'Ai Screening', '2026-02-13', NULL, N'low', 0, N'{}'),
    (N'JD', N'AuthZ Framework Review', '2026-05-04', NULL, N'low', 0, N'{}'),
    (N'JD', N'National Minimum Wage', '2025-10-10', '2025-12-05', N'low', 0, N'{}'),
    (N'JD', N'Absence Job Relationships', '2025-11-19', '2025-12-09', N'low', 0, N'{"Target Q1":"2026-01-01"}'),
    (N'JD', N'Schedule Driven Absence Calculations', '2026-01-01', '2026-01-31', N'low', 0, N'{}'),
    (N'JD', N'AE Letters', '2025-11-03', '2026-03-13', N'low', 1, N'{"Team to start work":"2025-11-17"}'),
    (N'JD', N'Pensioner Payroll', '2026-02-16', '2026-03-13', N'low', 1, N'{"Finish Analysis":"2026-03-06","Q2 Start":"2026-04-01"}'),
    (N'JD', N'Claims Approvals', '2025-10-20', '2026-03-31', N'low', 1, N'{"Team to start work":"2026-10-01","HLD Handover":"2026-02-20"}'),
    (N'JD', N'Gross to Net', '2026-03-09', '2026-04-30', N'low', 0, N'{}'),
    (N'JD', N'Inheritance Wiki Writeup', '2025-06-01', '2026-04-30', N'low', 0, N'{}'),
    (N'JD', N'AI PRD Evaluator', '2026-03-03', '2026-05-31', N'low', 0, N'{}'),
    (N'JD', N'Pay Period Review Log', '2025-12-05', '2026-05-31', N'low', 0, N'{}'),
    (N'JD', N'Payroll Automation (Scheduling + AE)', '2025-10-24', '2026-05-31', N'low', 0, N'{"Team Likely to Start":"2026-10-01","HLD Handover":"2026-02-20"}'),
    (N'JD', N'Smart Architecture Governance', '2025-01-01', '2026-12-31', N'low', 0, N'{}'),
    (N'Tim', N'Learning - Go1 Integration - PENS', '2026-01-28', '2026-06-26', N'high', 0, N'{}'),
    (N'Tim', N'Shared Read Models - Feature Team Support', '2025-11-01', NULL, N'medium', 0, N'{}'),
    (N'Tim', N'Auth Architecture for Finance', '2026-03-09', '2026-04-14', N'medium', 0, N'{}'),
    (N'Tim', N'Auth Issue Mitigations - User Offboarding and Rejoining', '2026-03-27', '2026-04-17', N'medium', 0, N'{}'),
    (N'Tim', N'Customer Environment Blueprinting App - Architecture Review', '2026-04-10', '2026-04-17', N'medium', 0, N'{}'),
    (N'Tim', N'Org Security (Phase 2) - Review Architecture Needs', '2026-02-26', '2026-04-17', N'medium', 0, N'{"Product HL approach proposed":"2026-02-26","feature teams start":"2026-04-01"}'),
    (N'Tim', N'SMS Fraud - User Creation Re-architecture', '2026-02-09', '2026-04-17', N'medium', 0, N'{}'),
    (N'Tim', N'ASQ 153 - Learning Surveys - Post Learning Event Surveys', '2026-01-26', '2026-05-01', N'medium', 0, N'{}'),
    (N'Tim', N'Org Security (Phase 2) - Soln Architecture', '2026-02-26', '2026-05-01', N'medium', 0, N'{"Product HL approach proposed":"2026-02-26","feature teams start":"2026-04-01"}'),
    (N'Tim', N'Org Security (Phase 2) - Feature Team Support', '2026-04-01', '2026-06-30', N'medium', 0, N'{"feature teams start":"2026-04-01"}'),
    (N'Tim', N'Customer Support - General Authn Issues', '2025-11-28', '2026-12-31', N'medium', 0, N'{}'),
    (N'Tim', N'Org Security (Standard User Role) - Update Architecture Docs', '2026-03-09', '2026-04-07', N'low', 0, N'{}'),
    (N'Tim', N'Architecture Standards - IdP Key Retrieval, Caching, and Validity', '2026-03-16', '2026-04-17', N'low', 0, N'{"requested cybersecurity review":"2026-03-31"}'),
    (N'Tim', N'Org Security - Removal of ''Everyone'' Role', '2026-02-02', '2026-04-17', N'low', 0, N'{}'),
    (N'Tim', N'Ping Federate Support - Public Integration Documentation', '2026-03-19', '2026-04-17', N'low', 0, N'{}'),
    (N'Tim', N'Ping Federate Support (Refresh of ID Tokens) - Customer Support', '2026-04-09', '2026-04-24', N'low', 0, N'{}'),
    (N'Tim', N'Approvals - Update Service Catalogue Documentation', '2026-01-19', '2026-05-01', N'low', 0, N'{}'),
    (N'Tim', N'Client Credentials for API access - Spike', '2026-04-06', '2026-05-01', N'low', 0, N'{}'),
    (N'Tim', N'Mobile App Working Group - Actions', '2026-03-09', '2026-05-06', N'low', 0, N'{}'),
    (N'Tim', N'Shared Read Models - Deployment Options', '2026-04-20', '2026-05-22', N'low', 0, N'{}');

COMMIT TRAN;
PRINT 'Imported 64 task(s).';
